services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_CREDENTIALS_FILE: /run/secrets/wordpress_credentials
    secrets:
      - db_password
      - wordpress_credentials
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${HOST_HTTPS_PORT:-443}:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html:ro
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wordpress_credentials:
    file: ../secrets/credentials.txt