FROM debian:11

RUN apt-get update \
 && apt-get install -y nginx openssl gettext-base \
 && rm -rf /var/lib/apt/lists/*

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/ssl/private /etc/ssl/certs

RUN openssl req -x509 -nodes -days 365 \
 -subj "/CN=hchowdhu.42.fr" \
 -newkey rsa:2048 \
 -keyout /etc/ssl/private/nginx.key \
 -out /etc/ssl/certs/nginx.crt

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]